[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14"
anyhow = "1.0"
smallvec = "1.13"
sscanf = "0.4.2"
regex = "1.11.1"
boolinator = "2.4.0"
fxhash = "0.2.1"
common = { path = "../common" }